// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctlyrmjspccerybcyegn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0bHlybWpzcGNjZXJ5YmN5ZWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzA3MzIsImV4cCI6MjA2MTI0NjczMn0.2d4C0z2tFgCJN4PfMLEo4pdMQPABKi-PQZXOa6rFW14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);